---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      require:
        - rubocop-rails
        - standard
      inherit_gem:
        standard:
          - config/base.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
