repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: 'config/credentials.yml.enc'
      - id: check-yaml
      - id: check-added-large-files
      - id: sort-simple-yaml
        files: '^bundler/config$'
      - id: check-toml
  - repo: https://github.com/benjamineskola/pre-commit-hooks.git
    rev: 4694d5d2d983956a41650cb2765755106eba23e9
    hooks:
      - id: prettier
      - id: rome
  - repo: local
    hooks:
      - id: standardrb
        name: standardrb
        language: system
        types: [ruby]
        entry: bundle exec standardrb --fix
      - id: erb-lint
        name: erb-lint
        language: system
        entry: bundle exec erblint --lint-all --autocorrect
        files: "(\\.erb)$"
      - id: rspec
        name: rspec
        language: system
        entry: bundle exec rspec
        types: [ruby]
        pass_filenames: false

exclude: '^bin/'
