repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: 'config/credentials.yml.enc'
      - id: check-yaml
      - id: check-added-large-files
      - id: sort-simple-yaml
        files: '^bundler/config$'
      - id: check-toml
  - repo: https://github.com/benjamineskola/pre-commit-hooks.git
    rev: 8898e97256c2e5248fe3feff59c5d30c816b3f6b
    hooks:
      - id: shellcheck
      - id: shfmt
      - id: prettier
      - id: rubocop
      - id: rome
  - repo: local
    hooks:
      - id: erb-lint
        name: erb-lint
        language: system
        entry: erblint --lint-all --autocorrect
        files: "(\\.erb)$"
      - id: rspec
        name: rspec
        language: system
        entry: rspec --format=failures --fail-fast
        types: [ruby]
        pass_filenames: false
