repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: 'config/credentials.yml.enc'
      - id: check-yaml
      - id: check-added-large-files
      - id: sort-simple-yaml
        files: '^bundler/config$'
      - id: check-toml
  - repo: https://github.com/benjamineskola/pre-commit-hooks.git
    rev: af21d0fdea02731583f480bb508fc4dac9ccb703
    hooks:
      - id: shellcheck
      - id: shfmt
      - id: prettier
      - id: rubocop
  - repo: local
    hooks:
      - id: erb-lint
        name: erb-lint
        language: system
        entry: erblint --lint-all --autocorrect
        files: "(\\.erb)$"
