require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - standard

inherit_gem:
  standard:
    - config/base.yml

AllCops:
  Exclude:
    - bin/*
    - vendor/*
  NewCops: enable

Layout/LineLength:
  Enabled: true
  AllowedPatterns: ['^\s*#']

Rails/I18nLocaleTexts:
  Enabled: false
