version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - .:/app
  app:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    tmpfs:
      - /app/app/assets/builds
      - /app/public/assets
      - /app/tmp
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/booklogger'
volumes:
  data:
